
#logging.level.root=debug

server.port=9001

spring.datasource.url=jdbc:postgresql://dpg-d7pr79rbc2fs73931l80-a.oregon-postgres.render.com/inventory_api_ezjb
spring.datasource.username=inventory_api_ezjb_user
spring.datasource.password=SzcphHA7kYO5qxROPZ1kIguY8NM6YRfd

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.security=DEBUG

app.jwt.secret=i-am-a-super-secret-i-am-a-super-secret-i-am-a-super-secret
app.jwt.expirationMinutes=60